palavra/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("entrar/", views.entrar, name="entrar"),
    path("cadastrar/", views.cadastrar, name="cadastrar"),
    path("jogo/", views.jogo, name="jogo"),
    path('pontos/', views.pontos_view, name='pontos_view'),
    path("configuracoes/", views.configuracoes, name="configuracoes"),
    path("ranking/", views.mostrar_ranking_melhores, name="ranking"),
    path("sair/", views.sair, name="sair"),
    path('deletar_conta/', views.deletar_conta, name='deletar_conta'),
]

termooo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('palavra.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

palavra/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.exceptions import ValidationError

class Usuario(AbstractUser):
    pontuacao_total = models.IntegerField(default=0)
    foto_perfil = models.ImageField(upload_to='palavra/foto_perfil/', null=True, blank=True)

    def __str__(self):
        return self.username

class Tema(models.Model):   
    descricao = models.CharField(max_length=20)

    def __str__(self):
        return self.descricao

class Palavra(models.Model):
    FACIL = 'Fácil'
    MEDIO = 'Médio'
    DIFICIL = 'Difícil'

    DIFICULDADE_CHOICES = [
        (FACIL, 'Fácil'),
        (MEDIO, 'Médio'),
        (DIFICIL, 'Difícil'),
    ]

    descricao = models.CharField(max_length=5)
    dificuldade = models.CharField(max_length=10, choices=DIFICULDADE_CHOICES)
    tema = models.ForeignKey(Tema, on_delete=models.CASCADE)

    def __str__(self):
        return self.descricao

    def clean(self):
        if len(self.descricao) > 5:
            raise ValidationError('A descrição da palavra não pode ter mais de 5 caracteres.')

palavra/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
from .models import Usuario

class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Nome de Usuário', widget=forms.TextInput(attrs={
        'placeholder': 'Nome de Usuário',
        'required': 'required',
        'class': 'form-control'
    }))
    password = forms.CharField(label='Senha', widget=forms.PasswordInput(attrs={
        'placeholder': 'Senha',
        'required': 'required',
        'class': 'form-control'
    }))

    error_messages = {
        'invalid_login': (
            "Por favor, entre com um usuário e senha corretos. "
            "Note que ambos os campos diferenciam maiúsculas e minúsculas."
        ),
        'inactive': ("Esta conta está inativa."),
    }

class CadastroForm(UserCreationForm):
    email = forms.EmailField(label='E-mail', widget=forms.EmailInput(attrs={
        'placeholder': 'E-mail',
        'class': 'form-control'
    }))
    username = forms.CharField(label='Nome de Usuário', widget=forms.TextInput(attrs={
        'placeholder': 'Nome de Usuário',
        'class': 'form-control'
    }))
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput(attrs={
        'placeholder': 'Senha',
        'class': 'form-control'
    }))
    password2 = forms.CharField(label='Confirme a Senha', widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirme a Senha',
        'class': 'form-control'
    }))

    class Meta(UserCreationForm.Meta): 
        model = Usuario
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if Usuario.objects.filter(email=email).exists():
            raise forms.ValidationError('Este e-mail já está cadastrado!')
        return email

class UserInfoForm(forms.ModelForm):
    foto_perfil = forms.ImageField(widget=forms.FileInput())

    username = forms.CharField(label='Nome de Usuário', widget=forms.TextInput(attrs={
        'placeholder': 'Nome de Usuário',
        'class': 'form-control'
    }))
    email = forms.EmailField(label='E-mail', widget=forms.EmailInput(attrs={
        'placeholder': 'E-mail',
        'class': 'form-control'
    }))
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput(attrs={
        'placeholder': 'Senha',
        'class': 'form-control'
    }))

    class Meta:
        model = Usuario
        fields = ['username', 'email', 'foto_perfil']

    def __init__(self, *args, **kwargs):
        super(UserInfoForm, self).__init__(*args, **kwargs)
        self.fields['foto_perfil'].widget.attrs.update({
            'accept': 'image/*',
            'class': 'form-control-file'
        })

palavra/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from .forms import LoginForm, CadastroForm, UserInfoForm
import json

from .utils import get_palavra_aleatoria
from .models import Palavra, Tema, Usuario
from .termo import Termo, InvalidAttempt

# Página Inicial
def index(request):
    return render(request, 'palavra/index.html')

# Autenticação
def entrar(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('jogo')
    else:
        form = LoginForm(request)
    return render(request, 'palavra/login.html', {'form': form})

def cadastrar(request):
    if request.method == 'POST':
        form = CadastroForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('jogo')
    else:
        form = CadastroForm()
    return render(request, 'palavra/cadastro.html', {'form': form})

def sair(request):
    logout(request)
    return redirect('/')

def deletar_conta(request):
    if request.method == 'POST':
        usuario = request.user
        Usuario.objects.filter(id=usuario.id).delete()
        logout(request)
        
    return redirect('/')

# Lógica do jogo
@login_required(login_url='/entrar/')
@csrf_exempt
def jogo(request):
    usuario = request.user
    temas = Tema.objects.all()

    # Seleciona a palavra da jogada
    if 'palavra_correta' not in request.session or request.session.get('nova_palavra', False):
        request.session['palavra_correta'] = get_palavra_aleatoria()
        request.session['nova_palavra'] = False
        request.session['num_tentativas'] = 0

    palavra_correta = request.session['palavra_correta']

    if request.method == 'POST':
        try:
            dados = json.loads(request.body)
            palavra = dados.get('palavra', '').strip()

            if not palavra:
                return JsonResponse({'status': 'error', 'message': 'Nenhuma palavra fornecida'}, status=400)

            palavras_validas = Palavra.objects.values_list('descricao', flat=True)
            termo = Termo(palavra_correta, set(palavras_validas))

            try:
                result = termo.test_guess(palavra)
                
                if result.win:
                    usuario.pontuacao_total += 10
                    usuario.save()
                    request.session['nova_palavra'] = True
                    return JsonResponse({'status': 'success', 'result': result.to_dict(), 'win': True})
                
                request.session['num_tentativas'] += 1
                max_tentativas = 6

                if request.session['num_tentativas'] >= max_tentativas:
                    request.session['nova_palavra'] = True
                    request.session['num_tentativas'] = 0

                    return JsonResponse({'status': 'success', 'result': result.to_dict(), 'palavra_correta': palavra_correta, 'win': False, 'message': 'Tentativas esgotadas'})

                return JsonResponse({'status': 'success', 'result': result.to_dict(), 'win': False})

            except InvalidAttempt as e:
                return JsonResponse({'status': 'error', 'message': str(e)}, status=400)

        except json.JSONDecodeError:
            return JsonResponse({'status': 'error', 'message': 'Erro no formato da requisição'}, status=400)

        except Exception as e:
            return JsonResponse({'status': 'error', 'message': 'Erro inesperado: ' + str(e)}, status=500)

    return render(request, 'palavra/jogo.html', {
        'temas': temas,
        'usuario': usuario,
    })


@login_required
def pontos_view(request):
    usuario = request.user
    return JsonResponse({'pontuacao': usuario.pontuacao_total if usuario else 0})


# Configurações
@login_required(login_url='/palavra/entrar/')
def configuracoes(request):

    user = request.user
    try:
        user_info = Usuario.objects.get(username=user)
    except Usuario.DoesNotExist:
        user_info = None

    if request.method == 'POST':
        form = UserInfoForm(request.POST, request.FILES, instance=user_info)
        if form.is_valid():
            form.save()
            return redirect('configuracoes')
    else:
        form = UserInfoForm(instance=user_info)

    return render(request, 'palavra/configuracoes.html', {
        'form': form,
        'user_info': user_info
    })


# Features
@login_required(login_url='/palavra/entrar/')
def mostrar_ranking_melhores(request):
    if not request.user.is_authenticated:
        return redirect('/palavra/entrar/')
    
    jogadores = Usuario.objects.order_by('-pontuacao_total')[:5]
    ranking = {jogador.username: posicao + 1 for posicao, jogador in enumerate(jogadores)}

    return render(request, 'palavra/ranking.html', {'top_cinco': jogadores, 'ranking': ranking})

palavra/templates/palavra/beneficios.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Palavra | Benefícios</title>
    <link rel="icon" href="{% static 'img/assets/Logo - Wordle Vetor.png' %}" />
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/beneficios.css' %}" />
    <!-- JS -->
    <script
      src="https://kit.fontawesome.com/026675cdf7.js"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <header>
      <nav class="header-nav">
        <ul class="header-menu">
          <li class="header-elemento-menu"><i class="fa-solid fa-bars"></i></li>
          <li class="header-como-jogar">
            <i class="fa-solid fa-circle-question"></i>
          </li>
        </ul>
        <div class="header-logo">PALAVRA</div>
        <div class="header-menu">
          <li class="header-pontos">
            <i class="fa-solid fa-square-parking"></i>
            <span id="usuario-pontos">0</span> <span>pontos</span>
          </li>
          <li class="header-ranking">
            <i class="fa-solid fa-square-poll-vertical"></i>
          </li>
          <li class="header-usuario">
            <i class="fa-solid fa-circle-user"></i>
            <div class="header-usuario-info">
              <span id="cumprimento-logado">Bem-vindo(a) {{ nome }}</span>
            </div>
          </li>
          <li class="header-configuracao"><i class="fa-solid fa-gear"></i></li>
        </div>
      </nav>
    </header>
    <main>
      <div class="main-container">
        <div class="main-title">
          <i class="fa-solid fa-square-parking"></i>
          <h1>Benefícios e formas de pagamento</h1>
        </div>
        <div class="main-container-beneficios">
          <span
            >Assine a nossa plataforma para ter beneficios e elevar a sua
            jogabilidade!</span
          >
          <div class="main-beneficios">
            <div class="beneficio-card" id="beneficio-free">
              <h3 class="beneficio-card-title">Plano Fee</h3>
              <div class="beneficio-card-icon">
                <i class="fa-solid fa-star"></i>
              </div>
              <div class="beneficio-card-text">Gratuito</div>
              <span class="beneficio-card-span"
                >Experimente o desafio do Wordle sem compromissos!</span
              >
              <ul class="beneficio-card-list">
                <li class="beneficio-card-item">
                  Lorem Ipsum is simply dummy text
                </li>
                <li class="beneficio-card-item">
                  Lorem Ipsum is simply dummy text
                </li>
                <li class="beneficio-card-item">
                  Lorem Ipsum is simply dummy text
                </li>
              </ul>
              <button class="beneficio-card-btn">Plano Atual</button>
            </div>
            <div class="beneficio-card" id="beneficio-mensal">
              <h3 class="beneficio-card-title">Plano Mensal</h3>
              <div class="beneficio-card-icon">
                <i class="fa-solid fa-star"></i>
              </div>
              <div class="beneficio-card-text">R$ 00,00 / mês</div>
              <span class="beneficio-card-span"
                >Experimente o desafio do Wordle por um mês! Sem compromissos,
                cancele a qualquer momento.</span
              >
              <ul class="beneficio-card-list">
                <li class="beneficio-card-item">
                  Lorem Ipsum is simply dummy text
                </li>
                <li class="beneficio-card-item">
                  Lorem Ipsum is simply dummy text
                </li>
                <li class="beneficio-card-item">
                  Lorem Ipsum is simply dummy text
                </li>
              </ul>
              <button class="beneficio-card-btn">Escolher Plano</button>
            </div>
            <div class="beneficio-card" id="beneficio-anual">
              <h3 class="beneficio-card-title">Plano Anual</h3>
              <div class="beneficio-card-icon">
                <i class="fa-solid fa-star"></i>
              </div>
              <div class="beneficio-card-text">R$ 00,00 / anual</div>
              <div class="beneficio-card-economize">Economize 00%</div>
              <ul class="beneficio-card-list">
                <li class="beneficio-card-item">
                  Lorem Ipsum is simply dummy text
                </li>
                <li class="beneficio-card-item">
                  Lorem Ipsum is simply dummy text
                </li>
                <li class="beneficio-card-item">
                  Lorem Ipsum is simply dummy text
                </li>
              </ul>
              <button class="beneficio-card-btn">Escolher Plano</button>
            </div>
          </div>
        </div>
      </div>
    </main>
    <footer>
      <div class="footer-container">
        <span
          >Palavra - projeto de engenharia de software - inspirado no jogo
          <a href="https://www.nytimes.com/games/wordle/index.html">Wordle</a>
        </span>
      </div>
    </footer>
  </body>
</html>

palavra/templates/palavra/cadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/026675cdf7.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/login-cadastro.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsivo_login-cadastro.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="icon" href="{% static 'img/assets/Logo - Wordle Vetor.png' %}" />
    <title>Cadastro</title>
</head>
<body>
    <nav class="header">
        <a href="{% url 'index' %}" class="navbar-brand">Palavra</a>
    </nav>
    <main>
        <div class="container_main">
            <div class="content">
                <div class="cadastro">
                    <h1>Cadastre-se</h1>
                    <p class="subtitulo">Não tem uma conta ainda? Cadastre-se!</p>
                    <form method="post">
                        {% csrf_token %}
                        <div class="cadastro-inputs">
                            {{ form.username }}
                            {% if form.username.errors %}
                                <div class="error">{{ form.username.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="cadastro-inputs">
                            {{ form.email }}
                            {% if form.email.errors %}
                                <div class="error">{{ form.email.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="cadastro-inputs">
                            {{ form.password1 }}
                            {% if form.password1.errors %}
                                <div class="error">{{ form.password1.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="cadastro-inputs">
                            {{ form.password2 }}
                            {% if form.password2.errors %}
                                <div class="error">{{ form.password2.errors }}</div>
                            {% endif %}
                        </div>
                        <button type="submit" class="pagina__botao">Cadastrar</button>
                    </form>
                </div>
            </div>
        </div>
    </main>    

    <!-- FOOTER -->
    {% include "footer.html" %}
</body>
</html>

palavra/templates/palavra/configuracoes.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/026675cdf7.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/configuracoes.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">

    <title>Palavra</title>
    <link rel="icon" href="{% static 'img/assets/Logo - Wordle Vetor.png' %}" />
</head>

<body>
    <!-- HEADER -->
    {% include "header.html" %}

    <main>
        <!-- USUARIO JOGANDO -->
        <div class="container">
            <!-- CONFIGURACOES -->
            <h1 class="title-pagina">
                <i class="fa-solid fa-gear" aria-hidden="true"></i>
                Configurações
            </h1>

            <div class="configuracoes__container">
                <div class="configuracoes__sidebar-lateral">
                    <ul>
                        <li>
                            <a href="#" onclick="showContent('content1', this)" class="configuracoes__link-name active">
                                <svg width="20" height="16" viewBox="0 0 20 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M9.74365 8.64502L3.10303 15.2856C2.64404 15.7446 1.90186 15.7446 1.44775 15.2856L0.344238 14.1821C-0.114746 13.7231 -0.114746 12.981 0.344238 12.5269L5.05127 7.81983L0.344238 3.11279C-0.114746 2.65381 -0.114746 1.91162 0.344238 1.45752L1.44287 0.344238C1.90186 -0.114746 2.64404 -0.114746 3.09814 0.344238L9.73877 6.98486C10.2026 7.44385 10.2026 8.18604 9.74365 8.64502ZM19.1187 6.98486L12.478 0.344238C12.019 -0.114746 11.2769 -0.114746 10.8228 0.344238L9.71924 1.44775C9.26025 1.90674 9.26025 2.64893 9.71924 3.10303L14.4263 7.81006L9.71924 12.5171C9.26025 12.9761 9.26025 13.7183 9.71924 14.1724L10.8228 15.2759C11.2817 15.7349 12.0239 15.7349 12.478 15.2759L19.1187 8.63525C19.5776 8.18604 19.5776 7.44385 19.1187 6.98486Z"/>
                                </svg>
                                Perfil
                            </a>
                        </li>
                        <li>
                            <a href="#" onclick="showContent('content2', this)" class="configuracoes__link-name">
                                <svg width="20" height="16" viewBox="0 0 20 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M9.74365 8.64502L3.10303 15.2856C2.64404 15.7446 1.90186 15.7446 1.44775 15.2856L0.344238 14.1821C-0.114746 13.7231 -0.114746 12.981 0.344238 12.5269L5.05127 7.81983L0.344238 3.11279C-0.114746 2.65381 -0.114746 1.91162 0.344238 1.45752L1.44287 0.344238C1.90186 -0.114746 2.64404 -0.114746 3.09814 0.344238L9.73877 6.98486C10.2026 7.44385 10.2026 8.18604 9.74365 8.64502ZM19.1187 6.98486L12.478 0.344238C12.019 -0.114746 11.2769 -0.114746 10.8228 0.344238L9.71924 1.44775C9.26025 1.90674 9.26025 2.64893 9.71924 3.10303L14.4263 7.81006L9.71924 12.5171C9.26025 12.9761 9.26025 13.7183 9.71924 14.1724L10.8228 15.2759C11.2817 15.7349 12.0239 15.7349 12.478 15.2759L19.1187 8.63525C19.5776 8.18604 19.5776 7.44385 19.1187 6.98486Z"/>
                                </svg>
                                Jogabilidade
                            </a>
                        </li>
                        <li>
                            <form method="POST" action="{% url 'deletar_conta' %}" onsubmit="return confirm('Tem certeza de que deseja deletar sua conta?');">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-link configuracoes__link-name link-delete">
                                    <svg width="20" height="16" viewBox="0 0 20 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M9.74365 8.64502L3.10303 15.2856C2.64404 15.7446 1.90186 15.7446 1.44775 15.2856L0.344238 14.1821C-0.114746 13.7231 -0.114746 12.981 0.344238 12.5269L5.05127 7.81983L0.344238 3.11279C-0.114746 2.65381 -0.114746 1.91162 0.344238 1.45752L1.44287 0.344238C1.90186 -0.114746 2.64404 -0.114746 3.09814 0.344238L9.73877 6.98486C10.2026 7.44385 10.2026 8.18604 9.74365 8.64502ZM19.1187 6.98486L12.478 0.344238C12.019 -0.114746 11.2769 -0.114746 10.8228 0.344238L9.71924 1.44775C9.26025 1.90674 9.26025 2.64893 9.71924 3.10303L14.4263 7.81006L9.71924 12.5171C9.26025 12.9761 9.26025 13.7183 9.71924 14.1724L10.8228 15.2759C11.2817 15.7349 12.0239 15.7349 12.478 15.2759L19.1187 8.63525C19.5776 8.18604 19.5776 7.44385 19.1187 6.98486Z"/>
                                    </svg>
                                    Deletar conta
                                </button>
                            </form>
                        </li>                        
                    </ul>
                </div>
                <div class="configuracoes__main-content">
                    <div id="content1" class="configuracoes__content active">
                        <div class="configuracoes__perfil">
                            <div class="configuracoes__form-control">
                                <form method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
            
                                    <div class="form-group">
                                        {% if user_info and user_info.foto_perfil %}
                                            <div class="usuario__imagem">
                                                <img src="{{ user_info.foto_perfil.url }}" alt="Foto de Perfil" class="foto-perfil">
                                            </div>
                                        {% else %}
                                            <label for="id_foto_perfil">Foto de Perfil</label>
                                            <div class="circulo-usuario">
                                                <img src="{% static 'img/assets/icon-user.png' %}" alt="Imagem não disponível">
                                            </div>
                                        {% endif %}
                                        {{ form.foto_perfil }}   
                                        <button type="button" class="btn btn-danger mt-2" onclick="document.getElementById('id_foto_perfil').value = ''; document.querySelector('.configuracoes__imagem-perfil img').src = '{% static 'img/assets/icon-user.png' %}';">Limpar</button>
                                    </div>
                                    <br><br>
                                    <div class="form-group">
                                        <label for="id_username">Nome de Usuário</label>
                                        {{ form.username }}
                                    </div>
                                    <br><br>
                                    <div class="form-group">
                                        <label for="id_email">E-mail</label>
                                        {{ form.email }}
                                    </div>
                                    <br><br>
                                    <div class="form-group">
                                        <label for="id_password1">Senha</label>
                                        {{ form.password1 }}
                                    </div>
                                    <br><br>
                                    <button type="submit">Salvar Alterações</button>
                                </form>
                            </div>
                        </div>
                    </div>

                    <div id="content2" class="configuracoes__content">
                        Conteúdo 2 aqui
                    </div>

                    <div id="content3" class="configuracoes__content">
                        Conteúdo 3 aqui
                    </div>

                    <div id="content4" class="configuracoes__content">
                        Conteúdo 3 aqui
                    </div>
                </div>
            </div>

        </div>
    </main>
    <!-- FOOTER -->
    {% include "footer.html" %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

    <script src="{% static 'js/jogo.js' %}"></script>
    {% comment %} <script>
        // Optional: Add JavaScript to handle image preview and clear functionality
        document.getElementById('id_foto_perfil').addEventListener('change', function(event) {
            const [file] = this.files;
            if (file) {
                const img = this.previousElementSibling.querySelector('img');
                img.src = URL.createObjectURL(file);
                img.style.display = 'block';
            }
        });
    </script> {% endcomment %}
</body>

</html>

palavra/templates/palavra/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://kit.fontawesome.com/026675cdf7.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/login-cadastro.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
        <link rel="icon" href="{% static 'img/assets/Logo - Wordle Vetor.png' %}">
        <title>Login</title>
    </head>
    <body>
        <nav class="header">
            <a href="{% url 'index' %}" class="navbar-brand">Palavra</a>
        </nav>

        <main>
            <div class="container_main">
                <div class="content">
                    <div class="login">
                        <h1>entre</h1>
                        <p>Que bom vê-lo(a) novamente! entre e bora adivinhar uma palavrinha</p><br>
                        <form method="post" class="form-control">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="pagina__botao">Entrar</button>
                        </form>
                        {% if error %}
                            <p class="login-error" id="login-error">{{ error }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </main>

        {% include "footer.html" %}
    </body>
</html>

palavra/templates/palavra/teste.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   bgipaethiourehtpirhytoareiuh 
</body>
</html>